---
- name: install and start apache
  hosts: all
  remote_user: vagrant
  become: yes

  tasks:
  - name: install python bindings for SELinux
    apt: name={{item}} state=present
    with_items:
    - selinux-utils
    - python-selinux
    - python-semanage

  - name: test to see if SELinux is running
    command: getenforce
    register: sestatus
    changed_when: false

  - name: install apache
    yum: name=apache2 state=present

  - name: start apache
    service: name=apache2 state=started enabled=yes