---
- name: Ejemplos de modulos de ficheros y openssl
  hosts: webservers
  become: True
  tasks:
    - name: Crear fichero con contenido especificado
      copy: content="Esto es un ejemplo \n" dest="/tmp/prueba" backup=yes
    - name: Propiedades fichero
      file: path="/tmp/prueba" backup=yes mode="777" owner="agubuntu" group="demo" 