---
- name: Trabajar con modulos de comandos
  hosts: localhost
  become: True
  tasks:
    - command: uname -a removes=/tmp/noejecutar
    - expect: 
        command: passwd user001
        responses:
            (?i)password: "Password"
    



