---
- name: install python bindings for SELinux
  apt: name={{item}} state=present
  with_items:
  - selinux-utils
  - python-selinux
  - python-semanage

- name: test to see if SELinux is running
  command: getenforce
  register: sestatus
  changed_when: false